# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180409_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
